Improve autoregistrar

diff --git a/bin/autoregistrar b/bin/autoregistrar
--- a/bin/autoregistrar
+++ b/bin/autoregistrar
@@ -5,6 +5,24 @@ if [[ ! ("$#" == 2 && -f $1) ]]; then
   exit 1
 fi
 
-./swf/bin/registrar domains -s $1 $(find . -name domains.json -not -path "**/test/*")
-./swf/bin/registrar workflowTypes -s $1 -d $2 $(find . -name workflowTypes.json -not -path "**/test/*")
-./swf/bin/registrar activityTypes -s $1 -d $2 $(find . -name activityTypes.json -not -path "**/test/*")
+DOMAINS=$(find . -name domains.json -not -path "**/test/*")
+if [[ -z "$DOMAINS" ]]; then
+  echo "domains.json not found (searched recursively in the current folder)"
+  exit 1
+fi
+
+WORKFLOW_TYPES=$(find . -name workflowTypes.json -not -path "**/test/*")
+if [[ -z "$WORKFLOW_TYPES" ]]; then
+  echo "workflowTypes.json not found (searched recursively in the current folder)"
+  exit 1
+fi
+
+ACTIVITY_TYPES=$(find . -name activityTypes.json -not -path "**/test/*")
+if [[ -z "$ACTIVITY_TYPES" ]]; then
+  echo "activityTypes.json not found (searched recursively in the current folder)"
+  exit 1
+fi
+
+./swf/bin/registrar domains -s $1 $DOMAINS
+./swf/bin/registrar workflowTypes -s $1 -d $2 $WORKFLOW_TYPES
+./swf/bin/registrar activityTypes -s $1 -d $2 $ACTIVITY_TYPES
